### PR TITLE
"assessment answers all in picture"

### PR DESCRIPTION
**Pull request by jcmeyer10**

### CODE REVIEW

**Comment by GA-MEB** [comment]
The sketch looks pretty good (minus the server being missing). Also, don't forget that the controller is the operative element here, not the view - the controller calls the model to get data, passes that into the view to get the full response, and then takes the response and hands it off to the server.

**Comment by GA-MEB** [comment]
re: Q1
That explanation is a little off. Rails is an MVC framework for building web applications. It gives us the tools (including background machinery and template code) to rapidly spin up new applications capable of (a) responding to requests, (b) manipulating data, and (c) sending back responses.

**Comment by GA-MEB** [comment]
re: Q3,
What's the difference between our app receiving a PATCH request vs a GET? Are there any differences?

**Comment by GA-MEB** [comment]
1.75 of 3 (-0.25 on Q1, -0.5 on Q2, -0.5 on Q3)

Not bad! Just a few hang-ups here and there. Hopefully this was more clear after today's lesson.

**Comment by jcmeyer10** [comment]
Jeez Matt, you can't even say this to my face?!  We're in the same room.
For shame.

In all seriousness, I can resubmit if you want.  Today did nail some
concepts in.  I feel like I could go through that  rails-summation and do
that myself.

We use Rails as a framework for connecting the back end and the front end
with some powerful tools that are able to work with multiple backends.

On Thu, Oct 29, 2015 at 8:04 PM, Matt Brendzel notifications@github.com
wrote:

> Closed #29
> https://github.com/ga-wdi-boston/rails-overview-assessment/pull/29.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-wdi-boston/rails-overview-assessment/pull/29#event-449883862
> .

## 

Regards,
Jeff Meyer

857-206-3572

**Pull request closed without merging**
